if: tag IS blank

sudo: false

os:
  - linux
  - osx

language: node_js
node_js:
- '12'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npminstall


install:
  - npminstall
  - npminstall codecov

script:
  - npm run ci

after_script:
  - npminstall codecov && codecov