if: tag IS blank

language: node_js
node_js:
- '12'

cache:
  directories:
    - node_modules

before_install:
  - npm root -g
  - npm i npminstall && npminstall 


install: true

script:
  - npm run ci

after_script:
  - npminstall codecov && codecov